# Generated by Django 4.0.3 on 2022-03-24 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('Ice', 'Ice'), ('Rock', 'Rock'), ('Electric', 'Electric'), ('Fire', 'Fire'), ('Fairy', 'Fairy'), ('Steel', 'Steel'), ('Flying', 'Flying'), ('Water', 'Water'), ('Dragon', 'Dragon'), ('Bug', 'Bug'), ('Psychic', 'Psychic'), ('Fighting', 'Fighting'), ('Grass', 'Grass'), ('Normal', 'Normal'), ('Posion', 'Poison'), ('Ground', 'Ground'), ('Dark', 'Dark')], max_length=10),
        ),
    ]
