# Generated by Django 4.0.3 on 2022-03-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_pokemon_user_alter_pokemon_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('Fire', 'Fire'), ('Dark', 'Dark'), ('Ground', 'Ground'), ('Ice', 'Ice'), ('Grass', 'Grass'), ('Bug', 'Bug'), ('Dragon', 'Dragon'), ('Water', 'Water'), ('Electric', 'Electric'), ('Steel', 'Steel'), ('Rock', 'Rock'), ('Fairy', 'Fairy'), ('Normal', 'Normal'), ('Flying', 'Flying'), ('Psychic', 'Psychic'), ('Fighting', 'Fighting'), ('Posion', 'Poison')], max_length=10),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='battle',
            field=models.ManyToManyField(to='main_app.battle'),
        ),
    ]
