# Generated by Django 4.0.3 on 2022-03-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_battle_pokemon_gender_alter_pokemon_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('Status', 'Staus'), ('Special', 'Specila'), ('Physical', 'Physical')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='battle',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='collected',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('Posion', 'Poison'), ('Flying', 'Flying'), ('Dark', 'Dark'), ('Fairy', 'Fairy'), ('Fighting', 'Fighting'), ('Ground', 'Ground'), ('Normal', 'Normal'), ('Water', 'Water'), ('Bug', 'Bug'), ('Psychic', 'Psychic'), ('Dragon', 'Dragon'), ('Fire', 'Fire'), ('Grass', 'Grass'), ('Ice', 'Ice'), ('Electric', 'Electric'), ('Rock', 'Rock'), ('Steel', 'Steel')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Battle',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='leagues',
            field=models.ManyToManyField(to='main_app.league'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='moves',
            field=models.ManyToManyField(to='main_app.pokemonmove'),
        ),
    ]
