# Generated by Django 4.0.3 on 2022-03-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_league_name_alter_pokemon_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemonmove',
            options={'ordering': ['type']},
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('Psychic', 'Psychic'), ('Electric', 'Electric'), ('Fire', 'Fire'), ('Steel', 'Steel'), ('Normal', 'Normal'), ('Ice', 'Ice'), ('Water', 'Water'), ('Fighting', 'Fighting'), ('Bug', 'Bug'), ('Flying', 'Flying'), ('Ground', 'Ground'), ('Posion', 'Poison'), ('Dark', 'Dark'), ('Dragon', 'Dragon'), ('Rock', 'Rock'), ('Grass', 'Grass'), ('Fairy', 'Fairy')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pokemonmove',
            name='type',
            field=models.CharField(choices=[('Physical', 'Physical'), ('Special', 'Special'), ('Status', 'Status')], max_length=10),
        ),
    ]
