# Generated by Django 4.0.3 on 2022-03-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_pokemonmove_options_alter_pokemon_gender_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PokemonMove',
            new_name='Pokemon_move',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='moves',
            new_name='pokemon_moves',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Fairy', 'Fairy'), ('Dragon', 'Dragon'), ('Posion', 'Poison'), ('Grass', 'Grass'), ('Steel', 'Steel'), ('Psychic', 'Psychic'), ('Bug', 'Bug'), ('Rock', 'Rock'), ('Water', 'Water'), ('Fire', 'Fire'), ('Ice', 'Ice'), ('Dark', 'Dark'), ('Fighting', 'Fighting'), ('Ground', 'Ground'), ('Flying', 'Flying'), ('Electric', 'Electric')], max_length=10),
        ),
    ]
