# Generated by Django 4.0.3 on 2022-03-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_pokemonmove_pokemon_move_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pokemon_move',
            new_name='Move',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='pokemon_moves',
            new_name='moves',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('Fairy', 'Fairy'), ('Posion', 'Poison'), ('Electric', 'Electric'), ('Grass', 'Grass'), ('Fighting', 'Fighting'), ('Ice', 'Ice'), ('Bug', 'Bug'), ('Dragon', 'Dragon'), ('Psychic', 'Psychic'), ('Normal', 'Normal'), ('Rock', 'Rock'), ('Water', 'Water'), ('Ground', 'Ground'), ('Steel', 'Steel'), ('Dark', 'Dark'), ('Flying', 'Flying'), ('Fire', 'Fire')], max_length=10),
        ),
    ]
